# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 조홍석 | Hongseok Cho
title: Software Engineer (Java Backend Developer)
email: 318921@naver.com
website: https://ko-ing.github.io/

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  ko-ing
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Spring Framework를 사용한지 6개월된 주니어 <mark>Java Spring 개발자</mark>입니다. 

  React와 Node.js을 사용한 프로젝트를 하면서 웹 프로그래밍에 처음 발을 들여 놓았고, 6개월 간 회사에서 Java 개발을 하게 되면서 다양한 비즈니스 로직의 구현과 외부 API 연동 작업 등을 하였습니다.

  6개월 간 회사에서 백엔드 개발을 하면서 성능에서부터 배포까지의 과정에서 고려해야할 것이 정말 많다는 것을 배웠고, 각각의 고려할 사항들은 상황에 따라 다른 기술들이 사용된다는 것을 알았습니다. 
  
  기술을 사용하는 <strong>이유</strong>가 중요하다고 생각하여 기술에 대한 동작 원리를 깊게 공부하는 것을 좋아합니다. 현재는 주 1~2회 Spring Framework에 관한 스터디를 하고 있으며, 관련 책 <토비의 스프링 3.1>도 조금씩 읽고 있습니다.
  
  <mark>원리와 이유</mark>가 중요하다고 생각하는 이유는 팀 내에서의 커뮤케이션에도 영향을 끼치기 때문입니다. 특정 기술이나 패러다임의 원리와 적용할 이유를 이유를 알고 있어야 비지니스에 맞는 의견을 낼 수 있으며, 팀원들 주장의 배경 역시 이해하기 쉽기 때문입니다.

  <mark>팀과 비즈니스</mark>에 필요한 기술을 적재적소에 제대로 사용할 수 있는 개발자가 되고 싶습니다.

content:
  - title: Projects  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Spring 스터디
        link: https://www.notion.so/b7e50b56371b4b6abd3dc6339231ed58
        link_text: 스터디 웹사이트
        caption: 2020.12 - Present
        additional_links:
          - title:  Spring 스터디
            icon: fas fa-globe
            url: https://www.notion.so/b7e50b56371b4b6abd3dc6339231ed58
        description: | # this will include new lines to allow paragraphs
          <i>&lt;<strong>Spring Framework</strong>의 여러 패러다임과 기술을 공부하는 스터디&gt;</i>

          스프링 개발을 하면서 당연하게 사용했던 기술들을 다시 돌아보고 정확히 이해하고 싶어 스터디를 시작했습니다.

          스프링이 어떤 패러다임에 만들어졌는지, 객체지향과는 어떤 연관이 있는지 실감하고 있습니다. 이론적 배경을 알게 되며 기존에 이해가 덜 되었던 코드들도 이해가 되기 시작하는 것 같습니다.

          현재 3회차까지 진행하였으며, 진행한 주제는 다음과 같습니다. (관련 링크는 왼쪽에 있습니다.)
          - IoC와 스프링
          - Dependecny Injection
          - Jpa, Hibernate, JDBC
          - AOP
      
      - layout: left
        title: Reasonable Project
        link: https://github.com/ko-ing/reasonable-server
        link_text: reasonable-server
        caption: 2020.12 - Present
        additional_links:
          - title:  reasonable-client
            icon: fab fa-github
            url: https://github.com/ko-ing/reasonable-front
        description: |
          <i>&lt;<strong>사진 / 동영상 일기</strong>로 감정 상태를 기록하는 플랫폼&gt;</i>

          프론트에서 백엔드, 그리고 배포까지 전체를 혼자서 다루어 보고 싶어 공부하는 목적으로 하고 있는 프로젝트입니다.

          <strong>사용 스펙</strong>

          Frontend:
          - React

          Backend:
          - Java / Spring Framework


      - layout: left
        title: Lostfinder Project
        # link: github.com/sproogen
        # link_text: Project Website
        caption: 2020.02 - 2020.05
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        description: | # this will include new lines to allow paragraphs
          <i>&lt;NFC 칩 네임택을 통해 <strong>분실물</strong>을 찾아주는 플랫폼 프로젝트&gt;</i>

          현업에서 많이 사용하는 React와 Node.js(Express.js)를 처음 접한 프로젝트입니다. 학교 수업에서는 Html, Css, Javascript, Php만을 배웠기 때문에 익숙하지 않아 여러 고생을 많이한 프로젝트입니다.

          하드코딩 되어 있는 부분도 많고 디렉토리 구조, 파일 구조 등 부족한 부분이 많지만 ORM, Oauth연동 등 다양한 기술을 접해 보았고 git을 사용한 첫 협업이라는 점에서 배울 점이 많았습니다.

          <strong>사용 스펙</strong>

          Frontend:
          - React

          Backend:
          - Express.js


  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (주) 테크타카
        link: http://www.argoport.com/
        # link_text: boringcompany.com
        sub_title: Backend Developer | 백엔드 개발자
        caption: 2020.08 - Present
          
        description: | # this will include new lines to allow paragraphs
          <i>&lt;무엇이든 언제 어디에서 어디로든 움직일 수 있는 원스톱 물류 시스템&gt;</i>

          백엔드 자바 개발자로 일한

          - 1000만 건 병렬처리 

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Development
        description: | # this will include new lines to allow paragraphs
          Backend
          - Java, Node.js
          - Spring Boot, Spring Data JPA, ...
          - JPA, Hibernate
          - Gradle
          - Intellij, Visual Studio Code
    
          Database / Messaging
          - Postgresql
          - Cassandra
          - Elasticsearch
          - Apache Kafka

          Frontend
          - React
          - React Hook
          - React Context

          Team Collaboration Tool
          - Slack
          - Bitbucket, Github
          - Jira
          - Confluence

      - layout: left
        title: 언어 
        description: | # this will include new lines to allow paragraphs
          한국어 - 한국인입니다! :D

          English - fluent enough to use every day!

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Yonsei University | 연세대학교
        caption: 2017 - Present (휴학중, 3-2 수료)
        sub_title: Computer Science | 컴퓨터과학과
        # description: | # this will include new lines to allow paragraphs

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      다른 취미나 관심사
      - 운동(맨몸 운동, 조깅 등)
      - 바둑
      - 간단한 음주
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
