# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 조홍석 | Hongseok Cho
title: Java Backend Developer 
email: 318921@naver.com
website: https://ko-ing.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  ko-ing
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  현재 회사 생활을 시작한지 6개월된 주니어 <mark>자바 백엔드 개발자</mark>입니다. 

  아직 초보 개발자이지만, 하고 싶은 것과 배우고 싶은 것이 많습니다. 6개월 간 회사에서 백엔드 개발을 하면서 성능에서부터 배포까지 고려해야할 것이 정말 많다는 것을 배웠고, 각각의 고려할 사항들은 상황에 따라 다른 기술들이 사용된다는 것을 알았습니다. 
  
  깊게 공부하고 팀원과 공부한 것을 공유하기 좋아합니다. 깊게 공부를 하여야 그 기술을 사용하는 이유와 기술의 동작 방식을 알게 되고, 원인은 행동의 시작점이기 때문입니다. 현재는 스프링의 기초를 단단히 하고 싶어 스프링에 관한 스터디를 주 1~2회 하고 있으며, 관련 책 <토비의 스프링 3.1>도 읽고 있습니다. 
  
  원리와 이유가 중요하다고 생각하는 이유는 팀 내에서의 커뮤케이션에도 영향을 끼치기 때문입니다. 특정 기술이나 패러다임의 원리와 적용할 이유를 이유를 알고 있어야 비지니스에 맞는 의견을 낼 수 있으며, 팀원들 주장의 배경 역시 이해하기 쉽기 때문입니다.

content:
  - title: Projects  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Spring 스터디
        link: https://www.notion.so/b7e50b56371b4b6abd3dc6339231ed58
        link_text: Project Website
        caption: 2020.12 - Present
        additional_links:
          - title:  Spring 스터디
            icon: fas fa-globe
            url: https://www.notion.so/b7e50b56371b4b6abd3dc6339231ed58
        # quote: >
        #   스
        description: | # this will include new lines to allow paragraphs
          <mark>Spring Framework</mark>를 사용하면서 당연하게 사용했던 기술들을 다시 돌아보면서 정확히 이해하고 싶어 스터디를 시작했습니다.

          Spring Framework가 어떤 패러다임에 만들어졌는지, 객체지향과는 어떤 연관이 있는지 실감하고 있습니다. 이론적 배경을 알게 되며 기존에 이해가 덜 되었던 회사의 코드들도 이해가 되기 시작하는 것 같습니다.


      - layout: left
        title: 로스트 파인더 프로젝트
        link: github.com/sproogen
        # link_text: Project Website
        caption: 2020.08 - Present
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   NFC 칩 네임택을 통해 분실물을 찾아주는 플랫폼 프로젝트 (2020.02 ~ 2020.05)
        description: | # this will include new lines to allow paragraphs
          학교 수업 <인터넷 프로그래밍>에서 주로 Javascript와 php 등을 배워 현업에서 많이 사용하는 라이브러리나 프레임워크를 사용해 보지 못했습니다.
          
          이 프로젝트를
           현업에서 많이 쓰는 라이브러리나 프레임워크를 배우지 않았기 때문에 처음으로 React와 Express.js를 통해 

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (주) 테크타카
        link: http://www.argoport.com/
        # link_text: boringcompany.com
        sub_title: Backend Developer | 백엔드 개발자
        caption: 2020.08 - Present
        quote: >
          무엇이든 언제 어디에서 어디로든 움직일 수 있는 원스톱 물류 시스템
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Development
        description: | # this will include new lines to allow paragraphs
          Backend
          - Java, Node.js
          - Spring Boot, Spring Data JPA, ...
          - JPA, Querydsl, Hibernate
          - Gradle
          - Intellij, Visual Studio Code
    
          Database / Messaging
          - Postgresql
          - Cassandra
          - Elasticsearch
          - Apache Kafka

          Frontend
          - React
          
          Version Control System
          - git

          Team Collaboration Tool
          - Slack
          - Jira
          - Confluence

      - layout: left
        title: 언어 
        description: | # this will include new lines to allow paragraphs
          - 한국어 - 한국인입니다! :D
          - English - fluent enough to use it every day!

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Yonsei University | 연세대학교
        caption: 2017 - Present (휴학중, 3-2 수료)
        sub_title: Computer Science | 컴퓨터과학과
        # description: | # this will include new lines to allow paragraphs

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
